name: Build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: 8

    - uses: actions/setup-python@v1
      with:
        python-version: 2.7

    - name: Build
      run:  unset _JAVA_OPTIONS && bash mi8.sh

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
            mipay-MI8-*.zip
            eufix-MI8-*.zip
            eufix-appvault-MI8-*.zip
            eufix-force-fbe-oreo.zip
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
